version: "2"
run:
  issues-exit-code: 1
  tests: true
linters:
  enable:
    - revive
    - whitespace
    - errcheck
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/kinvolk/nebraska
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
