FROM alpine:3.10

RUN apk update && \
	apk add postgresql postgresql-contrib su-exec && \
	rm -rf /var/cache/apk

COPY docker/postgres-test-docker-entrypoint.sh /docker-entrypoint.sh
COPY docker/wait_for_db_ready.sh /wait_for_db_ready.sh

ENV PGDATA /nebraska/data
ENV NEBTMP /nebraska
EXPOSE 5432
CMD ["/docker-entrypoint.sh"]
