FROM alpine:3.10

RUN apk update && \
	apk add --virtual .build-deps curl && \
	apk add postgresql postgresql-contrib && \
	curl -o /usr/local/bin/gosu -sSL "https://github.com/tianon/gosu/releases/download/1.10/gosu-amd64" && \
	chmod +x /usr/local/bin/gosu && \
	apk del .build-deps && \
	rm -rf /var/cache/apk

COPY docker/postgres-docker-entrypoint.sh /docker-entrypoint.sh

ENV PGDATA /nebraska/data
ENV PGTLS /nebraska/tls
EXPOSE 5432
CMD ["/docker-entrypoint.sh"]
