version: '3'
services:
  rollerd:
    build:
      context: .
      dockerfile: Dockerfile.rollerd
    command: |
      sh -c '
        sleep 3
        LOGXI=* /coreroller/rollerd -http-static-dir=/coreroller/static'
    network_mode: host
    depends_on:
      - postgres
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    volumes:
      - postgres-data:/coreroller/data
    network_mode: host
volumes:
  postgres-data:
