# Docker-compose file for interactive and for automated testing.
# Inherits shared PostgreSQL service from docker-compose.base.yaml
#
# Build docker image from local sources:
#   docker compose -f docker-compose.base.yaml -f docker-compose.test.yaml build
#
# Run:
#   docker compose -f docker-compose.base.yaml -f docker-compose.test.yaml up
# Run with persistent storage:
#   docker compose -f docker-compose.base.yaml -f docker-compose.test.yaml -f docker-compose.pg-persist.yaml up
#
# See docker-compose.pg-persist.yaml for more information on persistent storage.

services:
  server:
    build:
      context: ../
      dockerfile: Dockerfile
      network: host
    ports:
      - "8002:8000"
    # Workaround for missing support for depends_on conditions in podman-compose:
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - NEBRASKA_DB_URL=postgres://postgres:nebraska@postgres:5432/nebraska_tests?sslmode=disable&connect_timeout=10
    command: sh -c "/nebraska/nebraska --auth-mode=noop --http-static-dir=/nebraska/static --api-endpoint-suffix=/"
