apiVersion: v1
kind: Service
metadata:
  name: {{ include "nebraska.fullname" . }}
  labels:
    {{- include "nebraska.labels" . | nindent 4 }}
  {{- with .Values.extraLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
  {{- with.Values.extraAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "nebraska.selectorLabels" . | nindent 4 }}
