name: Build Container Image
on:
  pull_request:
    paths:
    - 'backend/**'
    - 'frontend/**'
    - Makefile
    - '.github/**'
    - Dockerfile

permissions:
  contents: read

jobs:
  build:
    name: Build Container Image
    runs-on: ubuntu-24.04
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@99012661954931238ded8c8b007157a8430204e1 # v4.4.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069 # v4.4.1

    - name: Check out code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Build image
      env:
        DOCKER_BUILDKIT: 1
      run: |
        cd $GITHUB_WORKSPACE
        make container
