name: updater
on:
  pull_request:
    paths:
    - 'updater/**'

permissions:
  contents: read

jobs:
  build:
    name: Test updater library
    runs-on: ubuntu-24.04
    steps:
    - name: Check out code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Set up Go
      uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
      with:
        go-version-file: ./updater/go.mod
      id: go

    - name: Start postgres dependency
      run: |
        docker compose -f backend/docker-compose.test.yaml up -d postgres

    - name: Test library
      env:
        NEBRASKA_DB_URL: "postgres://postgres:nebraska@127.0.0.1:8001/nebraska_tests?sslmode=disable&connect_timeout=10"
      run: |
        cd updater
        go test -v ./...
